# Generated by Django 4.1.4 on 2022-12-27 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=127, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=127, unique=True)),
                ('state', models.JSONField(null=True)),
                ('who_win', models.CharField(choices=[('first', 'first'), ('second', 'second')], max_length=15, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('first_opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to='sea_battle_app.opponent')),
                ('second_opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='sea_battle_app.opponent')),
            ],
        ),
    ]
