# Generated by Django 4.1.4 on 2022-12-28 10:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sea_battle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opponent',
            new_name='Player',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='first_opponent',
            new_name='first_player',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='second_opponent',
            new_name='second_player',
        ),
    ]
