# Generated by Django 4.1.4 on 2023-01-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle_app', '0002_rename_opponent_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='whose_move',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second')], max_length=15, null=True),
        ),
    ]
