# Generated by Django 4.1.4 on 2023-01-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle_app', '0003_battle_whose_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='state',
            new_name='json_state',
        ),
    ]
