# Generated by Django 4.1.4 on 2023-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle_app', '0004_rename_state_battle_json_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='who_win',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='whose_move',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], null=True),
        ),
    ]
